[package]
name = "twitter_v2"
version = "0.1.8"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/jpopesculian/twitter-v2-rs"
documentation = "https://docs.rs/twitter-v2/"
repository = "https://github.com/jpopesculian/twitter-v2-rs"
description = "Twitter API v2"
keywords = ["twitter", "v2", "api", "client", "oauth"]
categories = ["web-programming::http-client"]

[features]
default = ["oauth2", "native-tls"]
rustls-tls = ["oauth2/rustls-tls", "reqwest/rustls-tls"]
native-tls = ["oauth2/native-tls", "reqwest/native-tls"]
arbitrary_precision = ["serde_json/arbitrary_precision"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
oauth1 = { version = "0.5", package = "oauth1-request" }
oauth2 = { version = "4.1", optional = true, default-features = false, features = ["reqwest"] }
percent-encoding = "2.1"
pin-project-lite = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream"] }
serde = {workspace = true}
serde_json = {workspace = true}
serde_urlencoded = "0.7"
strum = { version = "0.24", features = ["derive"] }
thiserror = {workspace = true}
time = { workspace = true}
tokio = { workspace =true } 
url = {workspace = true}

[dev-dependencies]
axum = "0.4.8"
lazy_static = "1.4.0"
rand = "0.8.5"
tower-http = { version = "0.2.5", features = ["trace"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
pretty_assertions = "1.2.0"
