[package]
name = "utils"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
rand = {workspace = true}
rsa = {workspace = true}
pkcs1 = {workspace = true}
serde_bytes = { workspace = true }
