[enclave]
cid = 10

[enclave.grpc]
vsock_port = 50001
tcp_port = 7000

[[enclave.tcp_proxies]]
local_tcp_port = 7000
remote_cid = 3
remote_port = 8000

[[enclave.tcp_proxies]]
local_tcp_port = 7001
remote_cid = 4
remote_port = 8001

[host]
listen_port = 9000

[[host.vsock_proxies]]
local_vsock_port = 9001
remote_host = "example.com"
remote_port = 8080

[[host.vsock_proxies]]
local_vsock_port = 9002
remote_host = "another-example.com"
remote_port = 8081

[trace]
prefix = "sig_server"
dir = "logs/"
level = "info"
console = true
flame = false